#!/usr/bin/env python3
"""Embed a validation HTML fixture as a C byte array header.

Used only by BROWSER_FILE_SMOKE=1 validation builds so a self-test document
can be seeded into the FAT32 volume and loaded through the ordinary
file:// -> NetSurf -> QuickJS pipeline (rather than a bespoke test harness
that would not exercise the real code path).
"""
import argparse, os, sys

def main():
    p = argparse.ArgumentParser()
    p.add_argument('--in', dest='src', required=True)
    p.add_argument('--out', dest='dst', required=True)
    p.add_argument('--symbol', default='browser_smoke_fixture_html')
    a = p.parse_args()
    with open(a.src, 'rb') as f:
        data = f.read()
    os.makedirs(os.path.dirname(os.path.abspath(a.dst)), exist_ok=True)
    lines = []
    lines.append('/* Generated by tools/gen_browser_fixture.py - do not edit. */\n')
    lines.append('#ifndef COS_BROWSER_SMOKE_FIXTURE_H\n#define COS_BROWSER_SMOKE_FIXTURE_H\n')
    lines.append('static const char %s[] = {\n' % a.symbol)
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        lines.append('    ' + ''.join('0x%02x,' % b for b in chunk) + '\n')
    lines.append('    0x00\n};\n')
    lines.append('static const unsigned int %s_len = %du;\n' % (a.symbol, len(data)))
    lines.append('#endif\n')
    with open(a.dst, 'w') as f:
        f.writelines(lines)
    print('browser fixture header written:', a.dst, '(%d bytes)' % len(data))
    return 0

if __name__ == '__main__':
    sys.exit(main())
