#!/usr/bin/env python3
"""Embed a .c-os ELF executable as a C byte array.

Kept separate from gen_browser_fixture.py because that tool hard-codes a
single header guard, so reusing it for a second embedded blob produced a
guard collision if both headers were ever included in one translation
unit. The guard here is derived from the symbol name.
"""
import argparse, os, sys

def main():
    p = argparse.ArgumentParser()
    p.add_argument('--in', dest='src', required=True)
    p.add_argument('--out', dest='dst', required=True)
    p.add_argument('--symbol', default='cos_program')
    a = p.parse_args()
    with open(a.src, 'rb') as f:
        data = f.read()
    guard = 'COS_EMBEDDED_%s_H' % a.symbol.upper()
    os.makedirs(os.path.dirname(os.path.abspath(a.dst)), exist_ok=True)
    out = ['/* Generated by tools/gen_cos_program.py from %s - do not edit. */\n'
           % os.path.basename(a.src),
           '#ifndef %s\n#define %s\n' % (guard, guard),
           'static const unsigned char %s[] = {\n' % a.symbol]
    for i in range(0, len(data), 12):
        out.append('    ' + ''.join('0x%02x,' % b for b in data[i:i+12]) + '\n')
    out.append('};\n')
    out.append('static const unsigned int %s_len = %du;\n' % (a.symbol, len(data)))
    out.append('#endif /* %s */\n' % guard)
    with open(a.dst, 'w') as f:
        f.writelines(out)
    print('embedded %d bytes as %s -> %s' % (len(data), a.symbol, a.dst))
    return 0

if __name__ == '__main__':
    sys.exit(main())
