#!/usr/bin/env python3
"""Embed a directory tree (the on-device SDK) as C data: a table of {path, data, len}.

Used to ship /system/sdk/include and /system/sdk/lib inside the kernel image; the boot-time
layout code (cos_system_layout.c) writes each entry to disk when it is missing or its size
differs. Paths are stored relative to the root given with --root and are emitted in sorted
order so the output is reproducible."""
import argparse, os, sys

def main():
    p = argparse.ArgumentParser()
    p.add_argument('--root', required=True)
    p.add_argument('--out', required=True)
    a = p.parse_args()
    files = []
    for d, _, names in os.walk(a.root):
        for n in names:
            full = os.path.join(d, n)
            files.append((os.path.relpath(full, a.root).replace(os.sep, '/'), full))
    files.sort()
    out = ['/* Generated by tools/gen_sdk_pack.py - do not edit. */\n',
           '#ifndef COS_SDK_PACK_H\n#define COS_SDK_PACK_H\n']
    total = 0
    for i, (rel, full) in enumerate(files):
        data = open(full, 'rb').read()
        total += len(data)
        out.append('static const unsigned char cos_sdk_f%d[] = {\n' % i)
        for k in range(0, len(data), 16):
            out.append('    ' + ''.join('0x%02x,' % b for b in data[k:k+16]) + '\n')
        if not data:
            out.append('    0\n')
        out.append('};\n')
    out.append('typedef struct { const char *path; const unsigned char *data; unsigned int len; } cos_sdk_file_t;\n')
    out.append('static const cos_sdk_file_t cos_sdk_files[] = {\n')
    for i, (rel, full) in enumerate(files):
        out.append('    { "%s", cos_sdk_f%d, %du },\n' % (rel, i, os.path.getsize(full)))
    out.append('};\n#define COS_SDK_FILE_COUNT %d\n#endif\n' % len(files))
    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    open(a.out, 'w').writelines(out)
    print('sdk pack: %d files, %d bytes -> %s' % (len(files), total, a.out))

if __name__ == '__main__':
    sys.exit(main())
