#!/bin/sh
# gen_stress_asset.sh - regenerate src/assets/wiki_stress_page.c
#
# The boot-time HTML/CSS/DOM/layout stress test
# (COS_VALIDATION_HTML_STRESS, see src/kernel/kernel.c) needs a real,
# large, messy web page compiled into the kernel. A hand-written test
# snippet is no substitute: the bugs this test exists to catch - a
# 16 MiB stack overflow and a NULL gui_misc_table entry reached only via
# the heap-exhaustion path - were both triggered by the sheer, ordinary
# complexity of a real article (nested tables, hundreds of links,
# citations, infoboxes, inline script), not by anything a person would
# think to write by hand.
#
# The generated file is ~4.6 MB of C source and is deliberately NOT kept
# in version control. Run this to produce it, then build with the test
# enabled:
#
#   sh tools/gen_stress_asset.sh
#   VALIDATION_HTML_STRESS=1 make
#
# Any reasonably large real page works; the default is chosen for being
# stable, text-heavy and representative.
set -e

URL="${1:-https://en.wikipedia.org/wiki/C_programming_language}"
OUT="src/assets/wiki_stress_page.c"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

echo "[gen] fetching $URL"
curl -sL -m 60 "$URL" -o "$TMP"
SIZE=$(wc -c < "$TMP")
echo "[gen] fetched $SIZE bytes"

if [ "$SIZE" -lt 10000 ]; then
    echo "[gen] ERROR: fetched page is implausibly small ($SIZE bytes)." >&2
    echo "[gen]        A tiny page would silently make the stress test" >&2
    echo "[gen]        meaningless rather than fail, so this stops here." >&2
    exit 1
fi

mkdir -p src/assets
python3 - "$TMP" "$OUT" << 'PYEOF'
import sys
src, dst = sys.argv[1], sys.argv[2]
data = open(src, 'rb').read()
with open(dst, 'w') as f:
    f.write("// GENERATED by tools/gen_stress_asset.sh - do not edit, do not commit.\n")
    f.write("// A real web page embedded for the boot-time HTML/CSS/DOM/layout\n")
    f.write("// stress test (COS_VALIDATION_HTML_STRESS in src/kernel/kernel.c).\n")
    f.write("#include <stdint.h>\n")
    f.write("const unsigned char wiki_stress_page[] = {\n")
    for i in range(0, len(data), 16):
        f.write("    " + ", ".join("0x%02x" % b for b in data[i:i+16]) + ",\n")
    f.write("};\n")
    f.write("const unsigned int wiki_stress_page_len = %d;\n" % len(data))
print("[gen] wrote %s (%d bytes of page data)" % (dst, len(data)))
PYEOF

echo "[gen] done. Build with: VALIDATION_HTML_STRESS=1 make"
